#!/usr/bin/env bash
# ==============================================================================
# scripts/compute-wasm-hashes.sh  (#664)
#
# Compute SHA-256 hashes for every built Mux Protocol release WASM and write
# them to a machine-readable manifest file (wasm-hashes.txt).
#
# This script is the CI counterpart of scripts/verify-wasm-hash.sh:
#   - compute-wasm-hashes.sh  — runs *after* the WASM build, produces the manifest
#   - verify-wasm-hash.sh     — runs *at deploy time*, verifies a single WASM
#
# Usage:
#   bash scripts/compute-wasm-hashes.sh [--wasm-dir <path>] [--out <file>]
#
# Options:
#   --wasm-dir <path>  Directory containing built .wasm files
#                      (default: target/wasm32-unknown-unknown/release)
#   --out <file>       Output manifest path
#                      (default: wasm-hashes.txt in the repo root)
#   --help             Show this help
#
# Output format (wasm-hashes.txt):
#   <sha256_hex>  <filename>
#   …
#   # Generated by compute-wasm-hashes.sh on <ISO-8601 date>
#
# CI upload:
#   Use `actions/upload-artifact` to publish wasm-hashes.txt alongside the
#   built WASMs so auditors and operators can reproduce the verification:
#
#     - uses: actions/upload-artifact@v4
#       with:
#         name: wasm-hashes
#         path: wasm-hashes.txt
#
# Exit codes:
#   0 — all hashes computed and written
#   1 — no WASM files found in the specified directory
#   2 — usage error
# ==============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WASM_DIR="${REPO_ROOT}/target/wasm32-unknown-unknown/release"
OUT_FILE="${REPO_ROOT}/wasm-hashes.txt"

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'

usage() {
  grep '^#' "$0" | head -40 | sed 's/^# \{0,1\}//'
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --wasm-dir) WASM_DIR="${2:?'--wasm-dir requires a value'}"; shift 2 ;;
    --out)      OUT_FILE="${2:?'--out requires a value'}";      shift 2 ;;
    --help|-h)  usage ;;
    *) echo "Unknown argument: $1" >&2; usage ;;
  esac
done

_sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# Collect the mux-* WASMs only (exclude any test artefacts).
shopt -s nullglob
wasms=("${WASM_DIR}"/mux_*.wasm)

if (( ${#wasms[@]} == 0 )); then
  echo -e "${RED}[ERROR]${NC} No mux_*.wasm files found in: ${WASM_DIR}" >&2
  echo "Run 'make wasm' or 'bash scripts/build-wasm.sh --release' first." >&2
  exit 1
fi

# ── Compute and write manifest ────────────────────────────────────────────────
{
  for wasm in "${wasms[@]}"; do
    hash=$(_sha256 "$wasm")
    basename "$wasm" | xargs printf "%s  %s\n" "$hash"
  done
  printf "# Generated by compute-wasm-hashes.sh on %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "${OUT_FILE}"

echo -e "${GREEN}==> WASM hashes written to: ${OUT_FILE}${NC}"
echo ""
cat "${OUT_FILE}"
echo ""
echo -e "${GREEN}✓ ${#wasms[@]} WASM(s) hashed.${NC}"
echo ""
echo "To verify a single WASM later:"
echo "  bash scripts/verify-wasm-hash.sh <wasm_file> <expected_sha256_hex>"
